### ISSUE TITLE
Cant get Axis camera to display picture with paparazzo

### ISSUE THREAD

**Issue by TTR77** [rodowi/Paparazzo.js#34]
Hi,

I've set up the demo and server.coffee script with cameras url and authentication  but I get no picture.

Anything else I should setup for it to work?

server.coffee
# Using the Paparazzo.js module

Paparazzo = require '../src/paparazzo'
http = require 'http'
url = require 'url'
auth = 'Basic ' + new Buffer('guest:guest').toString('base64')

paparazzo = new Paparazzo
    host: 'toube.no-ip.org'
    port: 85
    path: '/mjpg/1/video.mjpg'
    headers: { 'Authorization': auth }

updatedImage = ''

paparazzo.on "update", (image) =>
    updatedImage = image
    console.log "Downloaded #{image.length} bytes"

paparazzo.on 'error', (error) =>
    console.log "Error: #{error.message}"

paparazzo.start()

demo.html

```
        $(document).ready(function() {
            // Active camera will refresh every 2 seconds
            var TIMEOUT = 2000;
            var refreshInterval = setInterval(function() {
                var random = Math.floor(Math.random() * Math.pow(2, 31));
                $('img#camera').attr('src', 'http://toube.no-ip.org:85/camera?i=' + Math.random());
            }, TIMEOUT);    
        });

<body>
    <img src="" id="camera">
</body>
```

Any help is appreciated.

Br,
T

**Comment by Toubef** [comment]
Hi,

an update on this. I have now tested and installed node.js on my raspberrypi and now it works but it will not authenticate using the demo. I have added the appropriate user:pwd in the demo server.coffee file but keeps giving me the error of authentication failed.

any ideas?
I'm trying this using my Sony SNC-CX600W network camera.

demo server.coffee file looks like this:
```
# Using the Paparazzo.js module

Paparazzo = require '../src/paparazzo'
http = require 'http'
url = require 'url'
auth = 'Basic ' + new Buffer('guest:pwd').toString('base64')

# For a list of public cameras to test check:
# https://github.com/rodowi/Paparazzo.js/wiki/List-of-public-cameras

paparazzo = new Paparazzo
    host: 'tobba-home.no-ip.org'
    port: 1080
    path: '/'
    headers: { 'Authorization': auth }

updatedImage = ''

paparazzo.on "update", (image) =>
    updatedImage = image
    console.log "Downloaded #{image.length} bytes"

paparazzo.on 'error', (error) =>
    console.log "Error: #{error.message}"

paparazzo.start()

http.createServer (req, res) ->
    data = ''
    path = url.parse(req.url).pathname
        
    if path == '/camera' and updatedImage?
        data = updatedImage
        console.log "Will serve image of #{data.length} bytes"

    res.writeHead 200,
        'Content-Type': 'image/jpeg'
        'Content-Length': data.length

    res.write data, 'binary'
    res.end()
.listen(3000)

```
and demo.html like this:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script>
			$(document).ready(function() {
				// Active camera will refresh every 2 seconds
				var TIMEOUT = 2000;
				var refreshInterval = setInterval(function() {
					var random = Math.floor(Math.random() * Math.pow(2, 31));
					$('img#camera').attr('src', 'http://tobba-home.no-ip.org:1080/oneshotimage.jpg?i=' + Math.random());
				}, TIMEOUT);	
			});
		</script>
	</head>
	<body>
		<img src="" id="camera">
	</body>
</html>
```

Error:
![image](https://cloud.githubusercontent.com/assets/22622557/25311717/a47086f2-2810-11e7-9cf1-3b20f213cea8.png)

**Comment by Toubef** [comment]
Installing on my raspberry pi gives following error:
```
sudo make run
npm install
npm WARN paparazzo@0.5.1 No license field.
TypeError: path.exists is not a function
    at writeJs (/var/www/html/paparazzo/node_modules/coffee-script/lib/coffee-script/command.js:356:17)
    at compileScript (/var/www/html/paparazzo/node_modules/coffee-script/lib/coffee-script/command.js:145:18)
    at /var/www/html/paparazzo/node_modules/coffee-script/lib/coffee-script/command.js:110:18
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
Makefile:5: recipe for target 'compile' failed
make: *** [compile] Error 123
```

**Comment by Toubef** [comment]
Btw I'm using Nodejs version 7, is this compatible or should v6 be used?

**Comment by defvol** [comment]
@Toubef did downgrading to node v6 work for you?

that path.exists error looks like a deprecation of a method in core libraries
